### ISSUE TITLE
[Error] Compilation error in the first example

### ISSUE THREAD

**Issue by matejrisek** [slyons/rust-module-of-the-week#9]
Hi,

First of all - great initiative.

I'm a complete Rust noob and this is exactly what I was looking for - an easily digestible, short articles on Rust stdlib.

Now, when I try to execute the first example:
```rust
use std::{fs, io};

const PHOTO_HOME: &str = "/home/user/motw/week-1/";

fn main() {
    let entries = fs::read_dir(PHOTO_HOME)?
        .map(|entry_res| entry_res.map(|entry| entry.path()))
        .collect::<Result<Vec<_>, io::Error>>()?;

    println!("{:?}", entries);
}
```

I get the following error:
```
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`)
  --> src/main.rs:6:43
   |
5  | / fn main() {
6  | |     let entries = fs::read_dir(PHOTO_HOME)?
   | |                                           ^ cannot use the `?` operator in a function that returns `()`
7  | |         .map(|entry_res| entry_res.map(|entry| entry.path()))
8  | |         .collect::<Result<Vec<_>, io::Error>>()?;
9  | |
10 | |     println!("{:?}", entries);
11 | | }
   | |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `FromResidual<Result<Infallible, std::io::Error>>` is not implemented for `()`
   = note: required by `from_residual`

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`)
  --> src/main.rs:8:48
   |
5  | / fn main() {
6  | |     let entries = fs::read_dir(PHOTO_HOME)?
7  | |         .map(|entry_res| entry_res.map(|entry| entry.path()))
8  | |         .collect::<Result<Vec<_>, io::Error>>()?;
   | |                                                ^ cannot use the `?` operator in a function that returns `()`
9  | |
10 | |     println!("{:?}", entries);
11 | | }
   | |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `FromResidual<Result<Infallible, std::io::Error>>` is not implemented for `()`
   = note: required by `from_residual`
```
Version of Rust in use is:
```
stable-x86_64-unknown-linux-gnu (default)
rustc 1.54.0 (a178d0322 2021-07-26)
```

Could you provide hints on what could be wrong in my example?

Thanks in advance!

**Comment by eadgbear** [comment]
Hey! Thanks for the feedback and welcome to MOTW!

This is something that everyone learning Rust is going to run into, and it's an easy fix. One thing I'll point out is that the Rust compiler is (usually) pretty good about pointing out what's wrong. In this case, it's here:

```shell
 this function should return `Result` or `Option` to accept `?`
```

The `?` operator is some syntax sugar that for "If this is a `Result`, and that `Result` is an `Err`, return. Otherwise, get the value of the result. However, in order to be able to do that, the function or context in which you're using `?` has to return a `Result` with a matching `Error` type.

In this case, you'd change your `main` function to:
```rust
fn main() -> io::Result<()> {
// Rest of your code here

Ok(())
}
```
`io::Result<()>` here means that no matter what, this function is going to return either `Ok`, or `Err`. `io::Result` is an `std::io`-specific variety of Result that has an IO specific error type.  The last line is to make sure that when you're done in `main`, you return an `io::Result`'s success type, `Ok`, with the empty value `()`.

Hopefully this answers your question, and I hope you stay tuned for the `std::Result` module which will dig into this in greater detail.

**Comment by matejrisek** [comment]
Thanks a lot, indeed that helped. 

Looking forward to future articles :)
